# Exercice 1 "Perceptron simple"

In [1]:
import numpy as np

In [2]:
x=np.array([[1,1,0,0],[0,1,0,1],[1,0,1,1]])
t=np.array([[0,1,0],[0,1,1],[1,1,0]])


In [3]:
w = np.random.uniform(-1,1, size=(4, 3))
w

array([[ 0.92756286,  0.6888542 ,  0.9576959 ],
       [-0.72641902,  0.37332562, -0.76453808],
       [-0.73775754, -0.24699522,  0.39710017],
       [ 0.56527303,  0.05317157,  0.88546097]])

In [4]:
o=np.zeros((3,3))
o

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
t.transpose()

array([[0, 0, 1],
       [1, 1, 1],
       [0, 1, 0]])

In [6]:
def apprentissage(t,x,W,O):
  c = 0
  while (not(np.array_equal(t,O))):
    for i in range(np.shape(t)[0]):
      for j in range(np.shape(t)[1]):
        if (np.dot(x,W)[i,j]<0):
          O[i,j]=0
        else:
          O[i,j]=1
    W=W+0.3*np.dot(x.transpose(),(t-O))
    c+=1
  print("nombre d'itérations =",c)
  print(W)


In [7]:
apprentissage(t,x,w,o)

nombre d'itérations = 4
[[ 0.62756286  0.6888542  -0.2423041 ]
 [-1.02641902  0.37332562 -0.46453808]
 [-0.73775754 -0.24699522 -0.50289983]
 [ 0.56527303  0.05317157  0.58546097]]


In [8]:
np.array_equal(t,o)


True

# Exercice2 "perceptron de conjugaison"

1 word = (i j k) , i in {1,2,3},j in {4,5,6} , k in {7,8}

conjugate(word) = (i j k') , k' = 7 if k=8 , k'= 8 if k=7

exception : conugate(367)=367
1 word = (i j k) , i in {1,2,3},j in {4,5,6} , k in {7,8}

conjugate(word) = (i j k') , k' = 7 if k=8 , k'= 8 if k=7

exception : conugate(367)=367


In [9]:
#encoding
l1 = [[1,0,0], [0,1,0], [0,0,1]]
l2 = [[1,0],[0,1]]

In [10]:
l=[]
for i in l1:
  for j in l1:
    for k in l2:
      li=[]
      li.append(i)
      li.append(j)
      li.append(k)
      l.append(li)
l


[[[1, 0, 0], [1, 0, 0], [1, 0]],
 [[1, 0, 0], [1, 0, 0], [0, 1]],
 [[1, 0, 0], [0, 1, 0], [1, 0]],
 [[1, 0, 0], [0, 1, 0], [0, 1]],
 [[1, 0, 0], [0, 0, 1], [1, 0]],
 [[1, 0, 0], [0, 0, 1], [0, 1]],
 [[0, 1, 0], [1, 0, 0], [1, 0]],
 [[0, 1, 0], [1, 0, 0], [0, 1]],
 [[0, 1, 0], [0, 1, 0], [1, 0]],
 [[0, 1, 0], [0, 1, 0], [0, 1]],
 [[0, 1, 0], [0, 0, 1], [1, 0]],
 [[0, 1, 0], [0, 0, 1], [0, 1]],
 [[0, 0, 1], [1, 0, 0], [1, 0]],
 [[0, 0, 1], [1, 0, 0], [0, 1]],
 [[0, 0, 1], [0, 1, 0], [1, 0]],
 [[0, 0, 1], [0, 1, 0], [0, 1]],
 [[0, 0, 1], [0, 0, 1], [1, 0]],
 [[0, 0, 1], [0, 0, 1], [0, 1]]]

In [11]:
X=[]
for i in range(18):
  X.append(sum(l[i], []))


In [12]:
X

[[1, 0, 0, 1, 0, 0, 1, 0],
 [1, 0, 0, 1, 0, 0, 0, 1],
 [1, 0, 0, 0, 1, 0, 1, 0],
 [1, 0, 0, 0, 1, 0, 0, 1],
 [1, 0, 0, 0, 0, 1, 1, 0],
 [1, 0, 0, 0, 0, 1, 0, 1],
 [0, 1, 0, 1, 0, 0, 1, 0],
 [0, 1, 0, 1, 0, 0, 0, 1],
 [0, 1, 0, 0, 1, 0, 1, 0],
 [0, 1, 0, 0, 1, 0, 0, 1],
 [0, 1, 0, 0, 0, 1, 1, 0],
 [0, 1, 0, 0, 0, 1, 0, 1],
 [0, 0, 1, 1, 0, 0, 1, 0],
 [0, 0, 1, 1, 0, 0, 0, 1],
 [0, 0, 1, 0, 1, 0, 1, 0],
 [0, 0, 1, 0, 1, 0, 0, 1],
 [0, 0, 1, 0, 0, 1, 1, 0],
 [0, 0, 1, 0, 0, 1, 0, 1]]

In [13]:
X=np.array(X)

In [14]:
T=X

In [15]:
aux=0
for i in range(1,18):
  aux=T[i][6]
  T[i][6]=T[i][7]
  T[i][7]=aux


In [16]:
T
T.transpose()

array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
       [1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

In [17]:
W = np.random.uniform(-1,1, size=(8,8))
O=np.zeros((18,8))

In [18]:
W

array([[ 0.72438741, -0.06225151,  0.07362495, -0.90284437,  0.84225196,
         0.80303227,  0.60427306, -0.28109006],
       [-0.38917417, -0.73662193, -0.93299985,  0.58092492, -0.74352666,
         0.31429184, -0.98620416,  0.13551543],
       [ 0.96236374,  0.02382004,  0.58564053, -0.24880879,  0.77830852,
         0.93235747,  0.5267579 , -0.9186774 ],
       [ 0.78646909,  0.89479408,  0.61573921, -0.20108099,  0.75758806,
        -0.58487991, -0.77591426,  0.22082216],
       [-0.74511093, -0.43327155,  0.71484072,  0.52521942, -0.65838767,
        -0.64973284, -0.71335565, -0.07795063],
       [-0.64362311, -0.25860303,  0.91586814,  0.8035363 , -0.30921475,
         0.39453722, -0.79859023,  0.21023135],
       [-0.5664018 ,  0.95352964, -0.95136992,  0.38112301, -0.66207502,
        -0.61088687, -0.56781499, -0.21393988],
       [ 0.34320262, -0.10461836,  0.66136601, -0.6941438 , -0.06051815,
        -0.78635904,  0.53859195, -0.32112165]])

In [19]:
O

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
apprentissage(T,X,W,O)

nombre d'itérations = 3
[[ 1.92438741 -1.26225151 -0.82637505 -0.30284437  0.24225196  0.80303227
   1.20427306 -0.28109006]
 [-0.68917417  1.36337807 -1.83299985 -0.31907508  0.45647334  0.61429184
  -0.08620416 -0.16448457]
 [-0.23763626 -1.17617996  2.08564053 -0.24880879  0.17830852  0.93235747
   0.5267579  -0.0186774 ]
 [-0.11353091 -0.00520592  0.61573921  1.89891901 -0.44241194 -0.58487991
   0.12408574  0.22082216]
 [-0.44511093 -0.13327155  0.71484072 -0.67478058  1.14161233 -0.64973284
  -0.41335565  0.52204937]
 [-0.34362311  0.04139697  0.61586814 -0.3964637  -0.90921475  0.69453722
  -0.49859023  0.21023135]
 [-0.2664018   0.35352964 -0.35136992  0.08112301 -0.36207502 -0.61088687
   2.43218501 -1.41393988]
 [-0.25679738  0.19538164 -0.23863399 -0.6941438  -0.36051815 -0.48635904
  -0.96140805  1.47887835]]


In [21]:
np.array_equal(T,O)


True

# Exercice 3 : Perceptron probabiliste

In [22]:
import random
import math

In [23]:
def apprentissage_proba(t,x,W,O):
  c = 0
  print("matrice des poids init",W)
  while (not(np.array_equal(t,O))):
    for i in range(np.shape(t)[0]):
      for j in range(np.shape(t)[1]):
        p= 1 /( 1 + math.exp(-np.dot(x,W)[i,j]))
        r= random.random()
        if (p<r):
          O[i,j]=0
        else:
          O[i,j]=1
    W=W+0.3*np.dot(x.transpose(),(t-O))
    c+=1
  print("nombre d'itérations =",c)
  print("matrice des poids finale" ,W)



In [24]:
x2=np.array([[1,1,0,0],[0,1,0,1],[1,0,1,1]])
t2=np.array([[0,1,0],[0,1,1],[1,1,0]])
o2=np.zeros((3,3))
w2 = np.random.uniform(-1,1, size=(4, 3))

In [25]:
apprentissage_proba(t2,x2,w2,o2)

matrice des poids init [[ 0.91300842  0.00992429 -0.56000524]
 [ 0.94084197 -0.25463128 -0.7342069 ]
 [-0.98601757  0.35242995 -0.75601042]
 [-0.77168955 -0.30688562  0.39657451]]
nombre d'itérations = 18
matrice des poids finale [[ 0.31300842  1.50992429 -2.36000524]
 [-2.65915803  1.84536872 -0.1342069 ]
 [ 0.81398243  0.95242995 -1.65601042]
 [-0.17168955  1.49311438  0.99657451]]


# Exercice4 : Apprentissage Par Retropropagation d'erreur

In [26]:
import numpy as np

In [27]:
x=np.array([[1],[2],[3]])
t=np.array([[0.1],[0.3],[0.7]])
W=np.array([[0.5,0.3,0.1],[0.3,0.2,0.1]]) #w = np.random.uniform(-1,1, size=(2, 3))
Z=np.array([[0.1,0.2],[0.3,0.4],[0.5,0.6]]) #z = np.random.uniform(-1,1, size=(3, 2))
epsilon=10**(-9) #précision
eta=1 #learning rate

In [28]:
def f(x) :
    return(1 / (1+np.exp(-x)))

In [29]:
# mise à jour de la matrice des weights
def maj(A,eta,d,m): 
    return(A+eta*np.dot(d,m.transpose()))

In [30]:
def apprentissage_retro_prop(x,t,W,Z,epsilon,eta) :
    c=0
    e=np.ones((3,1))
    o=np.zeros((3,1))
    while(np.linalg.norm(e)>epsilon):
        b=np.dot(W,x)
        h=f(b)
        a=np.dot(Z,h)
        o=f(a)
        e=t-o
        delta_sortie = e * o * (1 - o)
        Z=maj(Z,eta,delta_sortie,h)
        delta_cachée= h * (1 - h) * (np.dot(Z.transpose(),delta_sortie))
        W=maj(W,eta,delta_cachée,x)
        c +=1
    print("nombre d'itérations = ",c)
    print("erreur e \n", np.linalg.norm(e))

In [31]:
apprentissage_retro_prop(x,t,W,Z,epsilon,eta)

nombre d'itérations =  1152
erreur e 
 9.925983737057078e-10
