In [1]:
# Représenation de la labyrinthe
# -------
# |0|¤|1|
# |2|3|4|
# |5|¤|6|
# -------

# état initial = 0
# état final = 6
# ¤ est un obstacle

In [2]:
import numpy as np
import math
from random import random
alpha = 0.3
gamma = 0.5
iter_max = 7

In [3]:
Q=np.zeros((7,4))
#matrice des récompenses
R=np.array([(0,2,0,0),
            (0,2,0,0),
            (-2,-2,0,2),
            (0,0,-3,3),
            (-3,4,0,0),
            (2,0,0,0),(0,0,0,0)])
#matrice des actions possibles (les valeurs représentent les etats apres transition, 0 si action non possible)
# H B G D
m = np.array([(0, 3, 0, 0), 
              (0, 5, 0, 0), 
              (1, 6, 0, 4),
              (0, 0, 3, 5), 
              (2, 7, 4, 0), 
              (3, 0, 0, 0),(0,0,0,0)])


In [4]:
def proba_gibbs(Q,s,a,m):
    if m[s,a]==0:
        return (0)
    else:
        sum = 0
        for i in range(Q.shape[1]):
            if m[s,i]:
                sum+=math.exp(Q[s,i])
        p= math.exp(Q[s, a])/sum
        return(p)

In [5]:
def update_Q(Q,alpha,gamma,s,s2,a,r):
    Q[s,a]=(1-alpha)* Q[s,a] + alpha *(r + gamma* np.max(Q[s2])) 

In [6]:
def Q_learning(Q, R,m, alpha=0.3,gamma=0.5,iter_max=7):
    iter = 0
    #s=0 #i=0 = s-1
    while(iter<iter_max):
        iter+=1
        s=0
        while(s!=6):
            prob_distribution=[] #liste des probabilité de Gibbs (si l'action n'est pas possible alors l[i]=0)
            for a in range(4):
                prob_distribution.append(proba_gibbs(Q,s,a,m))
            # draw a random number and conclude the action (0(H),1(B),2(G) ou 3(D))
            # It returns a 1 sized list of elements chosen from [0,1,2,3] with a probability p=prob_distribution for each index.
            x = np.random.choice([0, 1, 2, 3], 1, p=prob_distribution)
            a = x[0]
            # i=s-1# s2= new state after being in state "s" and choosing action "a"
            s2 = m[s,a]-1
            r = R[s,a]
            update_Q(Q, alpha, gamma, s, s2, a, r)
            s=s2




In [7]:
print("old Q-table \n",Q)
Q_learning(Q, R,m, alpha=0.3,gamma=0.5,iter_max=10)
print("new Q-table \n",Q)

old Q-table 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
new Q-table 
 [[ 0.          3.5822711   0.          0.        ]
 [ 0.          0.68010913  0.          0.        ]
 [-0.51       -0.93        0.          3.97076217]
 [ 0.          0.         -0.81        4.67733541]
 [-0.9         3.8870099   0.53406084  0.        ]
 [ 1.173       0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]
